CREATE DATABASE IF NOT EXISTS helloroomie;

USE helloroomie;

DROP TABLE IF EXISTS AD_IMAGE;

DROP TABLE IF EXISTS IMAGE;

DROP TABLE IF EXISTS AD;

DROP TABLE IF EXISTS LOCALITY;

DROP TABLE IF EXISTS ZONE;

DROP TABLE IF EXISTS CITY;

DROP TABLE IF EXISTS USER;
